---
roles:
  - name: galaxyproject.galaxy
    src: https://github.com/galaxyproject/ansible-galaxy
    version: client-25.1
  - name: galaxyproject.pulsar
    version: 1.0.11
  - name: galaxyproject.miniconda
    version: 0.3.2
  - name: galaxyproject.cvmfsexec
    version: 1.1.1
  - name: usegalaxy_eu.tpv_auto_lint
    src: https://github.com/usegalaxy-eu/ansible-tpv-lint
    version: deploy-configs

collections:
  - name: galaxyproject.general
    version: 1.3.4
