---
roles:
  - name: galaxyproject.galaxy
    version: 0.11.3
  - name: galaxyproject.pulsar
    version: 1.0.11
  - name: galaxyproject.miniconda
    version: 0.3.2
  - name: galaxyproject.cvmfsexec
    version: 1.1.1
  - name: usegalaxy_eu.tpv_auto_lint
    src: https://github.com/usegalaxy-eu/ansible-tpv-lint
    version: deploy-configs
