---
# Deploy static content (this does not require any vaulted secrets)

- hosts: galaxyservers
  remote_user: "{{ galaxy_privileged_user }}"
  vars_files:
    - "{{ galaxy_version_file }}"
  roles:
    - role: usegalaxy_static
