---

- name: Snapshot CVMFS changes on stratum 1 servers
  hosts: cvmfsstratum1servers
  remote_user: "{{ galaxy_user }}"
  roles:
    - role: usegalaxy_cvmfs
      galaxy_cvmfs_snapshot: yes
  tags:
    - cvmfs
    - no-restart

- name: Wipe CVMFS cache on Galaxy servers
  hosts: galaxyservers
  remote_user: "{{ galaxy_user }}"
  roles:
    - role: usegalaxy_cvmfs
      galaxy_cvmfs_flush_cache: yes
  tags:
    - cvmfs
    - no-restart
