---

- name: Restart Galaxy
  hosts: galaxyservers
  remote_user: "{{ galaxy_privileged_user }}"
  tasks:
    - name: Gracefully Restart Galaxy
      command: "{{ galaxy_gravity_command }} --no-user graceful"
      environment:
        GRAVITY_CONFIG_FILE: "{{ gravity_config_file }}"
        GALAXY_DROPBOX_APP_CLIENT_ID: "{{ galaxy_dropbox_app_client_id }}"
        GALAXY_DROPBOX_APP_CLIENT_SECRET: "{{ galaxy_dropbox_app_client_secret }}"
