---
# Manage static Tool Shed configuration files

- name: Create Tool Shed config dir
  file: state=directory path={{ galaxy_toolshed_config_dir }}

- name: Install additional Tool Shed config files (static)
  copy: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items: galaxy_toolshed_config_files

- name: Install additional Tool Shed config files (template)
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items: galaxy_toolshed_config_templates

- name: Create Tool Shed configuration file
  template: src=tool_shed.ini.j2 dest={{ galaxy_toolshed_config_file }} backup=yes
  notify:
    - restart galaxy tool shed
