---
#
# WARNING: this is shared by both Test and Main
#

# FIXME:
#   - slurm-drmaa installed by hand

# No FUSE on Rockfish =(

_anvil_home_root: "/home/x-xcgalaxy"
_anvil_project_root: "/anvil/projects/x-mcb140147"
_anvil_scratch_root: "/anvil/scratch/x-xcgalaxy"
_anvil_instance_root: "{{ _anvil_project_root }}/{{ galaxy_instance_codename }}"

host_directories:
  - path: "{{ _anvil_home_root }}/bin"
    mode: "0755"
  - path: "{{ _anvil_home_root }}/etc"
    mode: "0750"
  - path: "{{ pulsar_root }}/log"
    mode: "0750"

host_files:
  - src: "files/pulsar/el8/tmpwatch"
    dest: "{{ _anvil_home_root }}/bin/tmpwatch"
    mode: "0755"

host_crontabs:
  # pulsar-clean-jobs is installed by infrastructure-playbook
  - id: "pulsar-clean-{{ galaxy_instance_codename }}-scratch"
    use_cron_file: false
    minute: "{{ 59 | random(seed=galaxy_instance_codename) }}"
    hour: "*/4"
    job: "{{ _anvil_home_root }}/bin/pulsar-clean-jobs {{ pulsar_staging_dir }} >> {{ pulsar_root }}/log/pulsar-clean-jobs.log 2>&1"
  - id: "pulsar-clean-{{ galaxy_instance_codename }}-amqp-consume"
    use_cron_file: false
    minute: "15"
    hour: "2"
    job: "{{ _anvil_home_root }}/bin/tmpwatch 7d {{ pulsar_persistence_dir }}/amqp_ack-anvil/consume"
  - id: "pulsar-clean-cvmfs-cache"
    use_cron_file: false
    minute: "30"
    hour: "*/6"
    job: "{{ _anvil_home_root }}/bin/tmpwatch --nodirs 4d {{ _anvil_scratch_root }}/cvmfs_cache"

miniconda_install: false
miniconda_update: false
miniconda_prefix: "/apps/anvil/external/apps/conda/2025.02"
miniconda_channels:
  - conda-forge
miniconda_conda_environments:
  "{{ _anvil_instance_root }}/venv-python":
    packages:
      - python=3.11
  #__curl@7.71:
  #  packages:
  #    - curl=7.71

supervisord_install: virtualenv-unprivileged
supervisord_prefix: "{{ _anvil_project_root }}/supervisor"
supervisord_conf_path: "{{ supervisord_prefix }}/etc/supervisord.conf"
supervisord_conf_dir: "{{ supervisord_prefix }}/etc/supervisord.d"
supervisord_log_dir: "{{ supervisord_prefix }}/var/log"
supervisord_run_dir: "{{ supervisord_prefix }}/var/run"
host_supervisor_configs:
  - "{{ galaxy_instance_codename }}_pulsar"

supervisord_unprivileged_command: "{ date; pgrep -u {{ ansible_user }} supervisord || '{{ supervisord_prefix }}/bin/supervisord' -c '{{ supervisord_conf_path }}'; } >> {{ supervisord_log_dir }}/supervisord-launch.log 2>&1"

pulsar_root: "{{ _anvil_instance_root }}/pulsar"
pulsar_restart_handler_name: supervisor restart pulsar
pulsar_persistence_dir: "{{ _anvil_scratch_root }}/{{ galaxy_instance_codename }}/pulsar/var"
pulsar_staging_dir: "{{ _anvil_scratch_root }}/{{ galaxy_instance_codename }}/staging"
#galaxy_root: not required

#pulsar_env:
#  PATH: "{{ miniconda_prefix }}/envs/__curl@7.71/bin:/cm/shared/apps/slurm/current/sbin:/cm/shared/apps/slurm/current/bin:/cm/shared/apps/spack/cpu/opt/spack/linux-centos8-zen/gcc-8.3.1/gcc-10.2.0-n7su7jf54rc7l2ozegds5xksy6qhrjin/bin:/home/xgalaxy/.local/bin:/home/xgalaxy/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin"

pulsar_supervisor_env:
  - PATH="{{ pulsar_venv_dir }}/bin:%(ENV_PATH)s"
  #- LD_LIBRARY_PATH="{{ miniconda_prefix }}/envs/__curl@7.71/lib:/cm/shared/apps/slurm/current/lib64"
  - SLURM_CONF="/run/slurm/conf/slurm.conf"

galaxy_user: x-xcgalaxy
pulsar_privsep_user: "{{ galaxy_user }}"
pip_virtualenv_command: "{{ _anvil_instance_root }}/venv-python/bin/python3 -m venv"
pip_extra_args: "--index-url https://wheels.galaxyproject.org/ --extra-index-url https://pypi.org/simple"

pulsar_pycurl_ssl_library: openssl
pulsar_drmaa_library_path: "{{ _anvil_instance_root }}/slurm-drmaa/lib/libdrmaa.so"

pulsar_job_metrics_plugins:
  - type: core
  - type: cpuinfo
    verbose: true
  - type: meminfo
  - type: uname
  - type: cgroup

pulsar_yaml_config:
  staging_directory: "{{ pulsar_staging_dir }}"
  persistence_directory: "{{ pulsar_persistence_dir }}"
  message_queue_url: "{{ pulsar_message_queue_url }}"
  sentry_dsn: "{{ pulsar_sentry_dsn }}"
  maximum_stream_size: 1048576  # 1 MB
  amqp_acknowledge: True
  amqp_ack_republish_time: 180
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  dependency_resolution:
    resolvers:
      - type: conda
        prefix: "{{ miniconda_prefix }}"
        auto_init: false
        auto_install: false
  managers:
    anvil:
      type: queued_drmaa
      preprocess_action_max_retries: 10
      preprocess_action_interval_start: 2
      preprocess_action_interval_step: 2
      preprocess_action_interval_max: 60
      postprocess_action_max_retries: 10
      postprocess_action_interval_start: 2
      postprocess_action_interval_step: 2
      postprocess_action_interval_max: 60
      min_polling_interval: 15

cvmfsexec_source: none
cvmfsexec_url: https://github.com/natefoo/cvmfsexec/archive/refs/heads/untar-no-preserve-times.tar.gz

cvmfsexec_files:
  - src: files/pulsar/galaxyproject.org.pub
    dest: /etc/cvmfs/keys/galaxyproject.org/galaxyproject.org.pub
  - src: files/pulsar/data.galaxyproject.org.pub
    dest: /etc/cvmfs/keys/galaxyproject.org/data.galaxyproject.org.pub
  - content: |
      CVMFS_SERVER_URL='http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@'
      CVMFS_KEYS_DIR=/etc/cvmfs/keys/galaxyproject.org
    dest: /etc/cvmfs/domain.d/galaxyproject.org.conf

cvmfsexec_local_options:
  - key: CVMFS_ALIEN_CACHE
    value: "{{ _anvil_scratch_root }}/cvmfs_cache"
  - key: CVMFS_QUOTA_LIMIT
    value: "-1"
  - key: CVMFS_SHARED_CACHE
    value: "no"
  - key: CVMFS_CLAIM_OWNERSHIP
    value: "yes"
  - key: CVMFS_HTTP_PROXY
    value: "DIRECT"
