#! /usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import sys

from galaxy.metadata.set_metadata import set_metadata

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(set_metadata())
